/**
 * Evidence-directed multi-family historical window runner — operator utility
 * only.
 *
 * Submits ONE explicitly approved, bounded, post-fork PulseChain historical
 * block window through the existing production sync pipeline
 * (`POST /api/sync/manual`) for all four supported source families at once
 * (`TRANSFERS`, `DEX`, `LP`, `STAKING`). It does not implement a new
 * ingestion architecture, does not modify `runWalletSync` or
 * `mergeCursorWindow`, and does not perform reorg detection or portfolio
 * materialization.
 *
 * A historical window submitted here is, by construction, disconnected from
 * the wallet's live SyncCursor for at least one family (that is the entire
 * point — it targets a gap the ordinary forward/backfill cursor has not
 * reached). `mergeCursorWindow` already refuses to move a cursor across a
 * disconnected gap (src/services/sync/sync-state-store.ts), so a successful
 * run here ingests raw + canonical ledger evidence for the window WITHOUT
 * advancing SyncCursor and WITHOUT claiming the wallet's historical coverage
 * is now contiguous. This runner relies on that existing invariant; it does
 * not attempt to force, bypass, or duplicate it.
 *
 * Known limitations this runner does NOT attempt to fix (out of scope):
 *   - Reorg detection (`detectReorgMismatch`, `ReorgEvent`,
 *     `markRawDataRangeReorged`) is not wired into production ingestion.
 *     Re-ingesting a block under a genuinely different blockHash is a
 *     pre-existing correctness gap this runner does not address.
 *   - Portfolio materialization: this runner NEVER calls rebuild or any
 *     equivalent materialization operation. PortfolioTokenBalance may remain
 *     stale relative to a newly ingested window until a separately
 *     authorized rebuild runs.
 *
 * Safety defaults:
 *   - Dry-run unless --execute is passed.
 *   - sourceFamilies is fixed to ["TRANSFERS", "DEX", "LP", "STAKING"] and is
 *     NOT an operator-supplied argument.
 *   - The fork-boundary check (classifyPulseChainBlockProvenance) runs in
 *     BOTH the dry-run and execute paths, before any HTTP call.
 *   - The block span is capped by the existing manual-sync limit
 *     (MANUAL_SYNC_MAX_BLOCK_SPAN, src/services/api/validation.ts) — the same
 *     limit POST /api/sync/manual itself enforces.
 *   - The policyLabel prefix `EVIDENCE_DIRECTED_WINDOW_V1:` is generated by
 *     the runner from the operator's `--reason`; the operator cannot type or
 *     override the prefix.
 *
 * Usage (dry-run, the safe default):
 *   npx tsx --conditions react-server scripts/evidence-directed-window-runner.ts \
 *     --wallet-address 0x... --chain-id 369 \
 *     --start-block 17233000 --end-block 17233999 \
 *     --reason "recover window 65 evidence"
 *
 * Usage (execute exactly one window):
 *   npx tsx --conditions react-server scripts/evidence-directed-window-runner.ts \
 *     --execute --wallet-address 0x... --chain-id 369 \
 *     --start-block 17233000 --end-block 17233999 \
 *     --reason "recover window 65 evidence"
 *
 * Required environment variables:
 *   DATABASE_URL  PostgreSQL connection string (direct read-only planning
 *                 queries; all mutations happen through the HTTP route)
 *   REDIS_URL     Redis connection string (required by server-env)
 *
 * The --conditions react-server flag is required because imported ingestion
 * service modules use the server-only guard, which is a no-op only under
 * that export condition.
 *
 * Exit behaviour:
 *   - Exits 0 on any clean stop (dry-run completion, execute completion,
 *     or a gate failure reported through the JSON summary).
 *   - Exits 1 on invalid arguments, missing environment, HTTP submission
 *     failure, poll timeout, or an unterminated/failed SyncRun.
 *   - Never prints DATABASE_URL, REDIS_URL, RPC URLs, secrets, or headers.
 */

import { fileURLToPath } from "url";
import { mkdir, appendFile } from "node:fs/promises";
import path from "node:path";

import { PULSECHAIN_FORK_BOUNDARY, PULSECHAIN_REFERENCE } from "@/config/chains";
import { classifyPulseChainBlockProvenance } from "@/services/chains/fork-provenance";
import { MANUAL_SYNC_MAX_BLOCK_SPAN } from "@/services/api/validation";

// ─── Fixed policy (not operator-overridable) ───────────────────────────────

export const WINDOW_CHAIN_ID = PULSECHAIN_REFERENCE.id;
export const WINDOW_SOURCE_FAMILIES = ["TRANSFERS", "DEX", "LP", "STAKING"] as const;
export const POLICY_LABEL_PREFIX = "EVIDENCE_DIRECTED_WINDOW_V1:";
export const MAX_REASON_SLUG_LENGTH = 64;

// ─── Reason slug / policyLabel (pure) ──────────────────────────────────────

/**
 * Deterministic lowercase [a-z0-9-] slug from an arbitrary operator reason.
 * Returns null when nothing sanitizable remains (empty, punctuation-only,
 * etc.) so the caller can fail closed rather than submit an empty label.
 */
export function slugifyReason(reason: string): string | null {
  const slug = reason
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, MAX_REASON_SLUG_LENGTH)
    .replace(/-$/g, "");
  return slug.length > 0 ? slug : null;
}

export type PolicyLabelResult =
  | { ok: true; policyLabel: string; slug: string }
  | { ok: false; reason: string };

/**
 * Builds the machine-generated, versioned policyLabel from the operator's
 * reason text. The `EVIDENCE_DIRECTED_WINDOW_V1:` prefix is fixed by this
 * function alone — nothing in the CLI layer can substitute or bypass it.
 */
export function buildPolicyLabel(reasonInput: string): PolicyLabelResult {
  const slug = slugifyReason(reasonInput);
  if (!slug) {
    return { ok: false, reason: "reason produced an empty slug after sanitization; provide a reason containing at least one letter or digit" };
  }
  return { ok: true, policyLabel: `${POLICY_LABEL_PREFIX}${slug}`, slug };
}

// ─── Pre-submit validation gates (pure) ────────────────────────────────────

export type GateResult = { ok: true } | { ok: false; reason: string };

export function validateChainId(chainId: number): GateResult {
  if (chainId !== WINDOW_CHAIN_ID) {
    return { ok: false, reason: `chainId must be ${WINDOW_CHAIN_ID} (PulseChain); got ${chainId}` };
  }
  return { ok: true };
}

export function validateBlockOrder(args: { startBlock: bigint; endBlock: bigint }): GateResult {
  if (args.startBlock > args.endBlock) {
    return { ok: false, reason: `startBlock ${args.startBlock} must be less than or equal to endBlock ${args.endBlock}` };
  }
  return { ok: true };
}

export function validateRangeSize(args: {
  startBlock: bigint;
  endBlock: bigint;
  maxBlockSpan?: bigint;
}): GateResult {
  const maxBlockSpan = args.maxBlockSpan ?? MANUAL_SYNC_MAX_BLOCK_SPAN;
  const span = args.endBlock - args.startBlock;
  if (span > maxBlockSpan) {
    return {
      ok: false,
      reason: `block span ${span} exceeds the operator limit of ${maxBlockSpan} blocks (the same limit POST /api/sync/manual enforces); use a smaller range`,
    };
  }
  return { ok: true };
}

/**
 * Mechanical hard stop against planning or submitting a window whose
 * startBlock does not classify as PULSECHAIN_POST_FORK
 * (`classifyPulseChainBlockProvenance`, src/services/chains/fork-provenance.ts).
 * Runs identically in both the dry-run and execute paths.
 */
export function validateForkBoundary(args: { startBlock: bigint }): GateResult {
  const provenance = classifyPulseChainBlockProvenance({
    chainId: WINDOW_CHAIN_ID,
    blockNumber: args.startBlock,
  });
  if (provenance !== "PULSECHAIN_POST_FORK") {
    return {
      ok: false,
      reason: `proposed startBlock ${args.startBlock} classifies as ${provenance}, not PULSECHAIN_POST_FORK; this runner must never plan or submit a window at or below the PulseChain fork boundary (lastInheritedBlock ${PULSECHAIN_FORK_BOUNDARY.lastInheritedBlock})`,
    };
  }
  return { ok: true };
}

export function validateWalletAddress(walletAddress: string): GateResult {
  if (!/^0x[a-fA-F0-9]{40}$/.test(walletAddress)) {
    return { ok: false, reason: `walletAddress must be a valid EVM address; got ${JSON.stringify(walletAddress)}` };
  }
  return { ok: true };
}

export function validateNoActiveOperation(args: { activeRunCount: number }): GateResult {
  if (args.activeRunCount > 0) {
    return {
      ok: false,
      reason: `${args.activeRunCount} active (PENDING/RUNNING) SyncRun(s) exist; refusing to submit while an operation is active`,
    };
  }
  return { ok: true };
}

export function validateNoPolicyLabelCollision(args: {
  policyLabel: string;
  existingPolicyLabels: readonly string[];
}): GateResult {
  if (args.existingPolicyLabels.includes(args.policyLabel)) {
    return { ok: false, reason: `a SyncRun with policyLabel "${args.policyLabel}" already exists` };
  }
  return { ok: true };
}

// ─── Request body builder (pure) ───────────────────────────────────────────

export function buildManualSyncRequestBody(args: {
  walletAddress: string;
  startBlock: bigint;
  endBlock: bigint;
  policyLabel: string;
}) {
  return {
    walletAddress: args.walletAddress,
    chainId: WINDOW_CHAIN_ID,
    sourceFamilies: [...WINDOW_SOURCE_FAMILIES],
    startBlock: args.startBlock.toString(),
    endBlock: args.endBlock.toString(),
    policyLabel: args.policyLabel,
  };
}

// ─── Cursor disconnection (pure) ───────────────────────────────────────────
//
// Mirrors the disconnected-gap comparison mergeCursorWindow already performs
// (src/services/sync/sync-state-store.ts) so the dry-run report can honestly
// state whether the requested window sits outside the family's existing
// cursor coverage, without re-deriving or duplicating cursor-merge logic.

export type CursorSnapshot = { fromBlock: bigint; toBlock: bigint } | null;

export type CursorDisconnection = "no_existing_cursor" | "disconnected" | "connected";

export function classifyCursorDisconnection(args: {
  cursor: CursorSnapshot;
  startBlock: bigint;
  endBlock: bigint;
}): CursorDisconnection {
  if (!args.cursor) {
    return "no_existing_cursor";
  }
  const disconnectedForward = args.startBlock > args.cursor.toBlock + 1n;
  const disconnectedBackward = args.endBlock + 1n < args.cursor.fromBlock;
  return disconnectedForward || disconnectedBackward ? "disconnected" : "connected";
}

export function cursorsIdentical(a: CursorSnapshot, b: CursorSnapshot): boolean {
  if (a === null && b === null) return true;
  if (a === null || b === null) return false;
  return a.fromBlock === b.fromBlock && a.toBlock === b.toBlock;
}

// ─── CLI argument parsing ───────────────────────────────────────────────────

export type RunnerCliOptions = {
  execute: boolean;
  walletAddress: string;
  chainId: number;
  startBlock: bigint;
  endBlock: bigint;
  reason: string;
  baseUrl: string;
  evidenceDir: string;
  pollIntervalMs: number;
  pollTimeoutMs: number;
};

export type RunnerCliParseResult =
  | { ok: true; options: RunnerCliOptions }
  | { ok: false; error: string };

export const RUNNER_CLI_USAGE = [
  "Usage: evidence-directed-window-runner [--execute]",
  "         --wallet-address <0x..> --chain-id <369>",
  "         --start-block <n> --end-block <n> --reason <text>",
  "         [--base-url <url>] [--evidence-dir <path>]",
  "         [--poll-interval-ms <n>] [--poll-timeout-ms <n>]",
  "",
  "  Dry-run is the default and never submits an HTTP POST.",
  "  sourceFamilies is fixed to [TRANSFERS, DEX, LP, STAKING] and cannot be",
  "  supplied on the command line.",
  "  --wallet-address, --chain-id, --start-block, --end-block, and --reason",
  "  are all required.",
].join("\n");

const DEFAULT_BASE_URL = process.env.OPERATOR_RUNNER_BASE_URL ?? "http://localhost:3000";
const DEFAULT_EVIDENCE_DIR = "operator-evidence/evidence-directed-window";
const DEFAULT_POLL_INTERVAL_MS = 5_000;
const DEFAULT_POLL_TIMEOUT_MS = 20 * 60 * 1000;

export function parseRunnerCliArgs(argv: readonly string[]): RunnerCliParseResult {
  let execute = false;
  let walletAddress: string | undefined;
  let chainId: number | undefined;
  let startBlock: bigint | undefined;
  let endBlock: bigint | undefined;
  let reason: string | undefined;
  let baseUrl = DEFAULT_BASE_URL;
  let evidenceDir = DEFAULT_EVIDENCE_DIR;
  let pollIntervalMs = DEFAULT_POLL_INTERVAL_MS;
  let pollTimeoutMs = DEFAULT_POLL_TIMEOUT_MS;

  const readValue = (flag: string, index: number): string | null => {
    const value = argv[index + 1];
    if (value === undefined || value.startsWith("--")) {
      return null;
    }
    return value;
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--execute") {
      execute = true;
      continue;
    }
    if (arg === "--wallet-address") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--wallet-address requires a value." };
      walletAddress = value.toLowerCase();
      index += 1;
      continue;
    }
    if (arg === "--chain-id") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value)) {
        return { ok: false, error: "--chain-id must be an unsigned integer." };
      }
      chainId = Number(value);
      index += 1;
      continue;
    }
    if (arg === "--start-block") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value)) {
        return { ok: false, error: "--start-block must be an unsigned integer." };
      }
      startBlock = BigInt(value);
      index += 1;
      continue;
    }
    if (arg === "--end-block") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value)) {
        return { ok: false, error: "--end-block must be an unsigned integer." };
      }
      endBlock = BigInt(value);
      index += 1;
      continue;
    }
    if (arg === "--reason") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--reason requires a value." };
      reason = value;
      index += 1;
      continue;
    }
    if (arg === "--base-url") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--base-url requires a value." };
      baseUrl = value;
      index += 1;
      continue;
    }
    if (arg === "--evidence-dir") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--evidence-dir requires a value." };
      evidenceDir = value;
      index += 1;
      continue;
    }
    if (arg === "--poll-interval-ms") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value) || Number(value) <= 0) {
        return { ok: false, error: "--poll-interval-ms must be a positive integer." };
      }
      pollIntervalMs = Number(value);
      index += 1;
      continue;
    }
    if (arg === "--poll-timeout-ms") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value) || Number(value) <= 0) {
        return { ok: false, error: "--poll-timeout-ms must be a positive integer." };
      }
      pollTimeoutMs = Number(value);
      index += 1;
      continue;
    }
    if (arg === "--source-families" || arg === "--sourceFamilies") {
      return { ok: false, error: "sourceFamilies is fixed to [TRANSFERS, DEX, LP, STAKING] and cannot be supplied on the command line." };
    }

    return { ok: false, error: `Unknown argument: ${arg}` };
  }

  if (walletAddress === undefined) return { ok: false, error: "--wallet-address is required." };
  if (chainId === undefined) return { ok: false, error: "--chain-id is required." };
  if (startBlock === undefined) return { ok: false, error: "--start-block is required." };
  if (endBlock === undefined) return { ok: false, error: "--end-block is required." };
  if (reason === undefined) return { ok: false, error: "--reason is required." };

  const walletGate = validateWalletAddress(walletAddress);
  if (!walletGate.ok) return { ok: false, error: walletGate.reason };

  return {
    ok: true,
    options: {
      execute,
      walletAddress,
      chainId,
      startBlock,
      endBlock,
      reason,
      baseUrl,
      evidenceDir,
      pollIntervalMs,
      pollTimeoutMs,
    },
  };
}

// ─── Env validation ─────────────────────────────────────────────────────────

const REQUIRED_ENV_VARS = ["DATABASE_URL", "REDIS_URL"] as const;

export type EnvCheckResult = { ok: true } | { ok: false; missing: readonly string[] };

export function checkEnv(env: Record<string, string | undefined>): EnvCheckResult {
  const missing = REQUIRED_ENV_VARS.filter((k) => !env[k]);
  return missing.length === 0 ? { ok: true } : { ok: false, missing };
}

// ─── Evidence records ───────────────────────────────────────────────────────

export type EvidenceRecord = {
  kind: "dry-run" | "execute" | "stop";
  at: string;
  [key: string]: unknown;
};

/** JSON.stringify replacer that serializes bigint as a decimal string. */
function bigintSafeReplacer(_key: string, value: unknown) {
  return typeof value === "bigint" ? value.toString() : value;
}

export function serializeEvidence(record: EvidenceRecord): string {
  return JSON.stringify(record, bigintSafeReplacer);
}

export async function writeEvidenceLine(evidenceDir: string, record: EvidenceRecord): Promise<void> {
  await mkdir(evidenceDir, { recursive: true });
  const filePath = path.join(evidenceDir, "evidence-directed-window-evidence.jsonl");
  await appendFile(filePath, `${serializeEvidence(record)}\n`, "utf8");
}

// ─── Runner DB client (narrow, injectable) ─────────────────────────────────

export type RunnerSyncRunRecord = {
  id: string;
  trigger: string;
  status: string;
  stage: string;
  sourceFamilies: readonly string[];
  startBlock: bigint | null;
  endBlock: bigint | null;
  warningCount: number;
  warningDetails: unknown;
  errorMessage: string | null;
  failedSourceFamily: string | null;
  failedFromBlock: bigint | null;
  failedToBlock: bigint | null;
};

export type RunnerDbClient = {
  syncCursor: {
    findUnique: (args: unknown) => Promise<{
      fromBlock: bigint;
      toBlock: bigint;
      blockHash: string | null;
    } | null>;
  };
  syncRun: {
    findMany: (args: unknown) => Promise<Array<{ policyLabel: string }>>;
    findUnique: (args: unknown) => Promise<RunnerSyncRunRecord | null>;
    count: (args: unknown) => Promise<number>;
  };
};

export async function getCursorForFamily(
  db: RunnerDbClient,
  args: { walletId: string; chainId: number; sourceFamily: (typeof WINDOW_SOURCE_FAMILIES)[number] },
): Promise<CursorSnapshot> {
  const cursor = await db.syncCursor.findUnique({
    where: {
      walletId_chainId_sourceFamily: {
        walletId: args.walletId,
        chainId: args.chainId,
        sourceFamily: args.sourceFamily,
      },
    },
    select: { fromBlock: true, toBlock: true, blockHash: true },
  });
  return cursor ? { fromBlock: cursor.fromBlock, toBlock: cursor.toBlock } : null;
}

export async function getCursorsForAllFamilies(
  db: RunnerDbClient,
  args: { walletId: string; chainId: number },
): Promise<Record<(typeof WINDOW_SOURCE_FAMILIES)[number], CursorSnapshot>> {
  const entries = await Promise.all(
    WINDOW_SOURCE_FAMILIES.map(async (sourceFamily) => [
      sourceFamily,
      await getCursorForFamily(db, { walletId: args.walletId, chainId: args.chainId, sourceFamily }),
    ] as const),
  );
  return Object.fromEntries(entries) as Record<(typeof WINDOW_SOURCE_FAMILIES)[number], CursorSnapshot>;
}

export async function listActivePolicyLabels(db: RunnerDbClient, chainId: number): Promise<string[]> {
  const runs = await db.syncRun.findMany({ where: { chainId }, select: { policyLabel: true } });
  return runs.map((r) => r.policyLabel);
}

export async function countActiveOperations(db: RunnerDbClient): Promise<number> {
  return db.syncRun.count({ where: { status: { in: ["PENDING", "RUNNING"] } } });
}

// ─── HTTP + polling ─────────────────────────────────────────────────────────

export type HttpResponse = { status: number; body: unknown };
export type HttpPost = (url: string, body: unknown) => Promise<HttpResponse>;
export type HttpGet = (url: string) => Promise<HttpResponse>;

export async function checkServerHealth(httpGet: HttpGet, baseUrl: string): Promise<GateResult> {
  let response: HttpResponse;
  try {
    response = await httpGet(`${baseUrl}/api/debug/health`);
  } catch (err) {
    return { ok: false, reason: `health check request failed: ${err instanceof Error ? err.message : String(err)}` };
  }
  const body = response.body as { data?: { status?: string } } | undefined;
  if (response.status !== 200 || body?.data?.status !== "ok") {
    return { ok: false, reason: `server health check did not report ok (status ${response.status})` };
  }
  return { ok: true };
}

export async function pollSyncRunToTerminal(
  db: RunnerDbClient,
  runId: string,
  deps: { now: () => Date; sleep: (ms: number) => Promise<void>; pollIntervalMs: number; pollTimeoutMs: number },
): Promise<{ ok: true; run: RunnerSyncRunRecord } | { ok: false; reason: "timeout"; lastRun: RunnerSyncRunRecord | null }> {
  const deadline = deps.now().getTime() + deps.pollTimeoutMs;

  for (;;) {
    const run = await db.syncRun.findUnique({ where: { id: runId } });
    if (run && (run.status === "COMPLETED" || run.status === "FAILED")) {
      return { ok: true, run };
    }
    if (deps.now().getTime() >= deadline) {
      return { ok: false, reason: "timeout", lastRun: run };
    }
    await deps.sleep(deps.pollIntervalMs);
  }
}

// ─── Orchestrator ───────────────────────────────────────────────────────────

export type RunnerDeps = {
  db: RunnerDbClient;
  resolveWallet: (args: { walletAddress: string; chainId: number }) => Promise<{ id: string; address: string } | null>;
  httpGet: HttpGet;
  httpPost: HttpPost;
  now: () => Date;
  sleep: (ms: number) => Promise<void>;
  writeEvidence: (record: EvidenceRecord) => Promise<void>;
};

export type RunnerSummary = {
  mode: "dry-run" | "execute";
  stoppedReason: string;
  detail?: string;
};

const REORG_LIMITATION_DISCLOSURE =
  "Reorg detection (detectReorgMismatch, ReorgEvent, markRawDataRangeReorged) is NOT wired into production ingestion. This runner does not detect or guard against re-ingesting a block under a different blockHash than a prior observation.";

const MATERIALIZATION_LIMITATION_DISCLOSURE =
  "This runner never calls rebuild or any portfolio materialization operation. Canonical ledger ingestion for this window may complete while PortfolioTokenBalance remains stale relative to it. A separate, explicitly authorized rebuild is required to refresh portfolio totals.";

export async function runEvidenceDirectedWindowRunner(
  options: RunnerCliOptions,
  deps: RunnerDeps,
): Promise<RunnerSummary> {
  const mode: "dry-run" | "execute" = options.execute ? "execute" : "dry-run";

  const chainIdGate = validateChainId(options.chainId);
  if (!chainIdGate.ok) return stop(deps, mode, "invalid_chain_id", chainIdGate.reason);

  const orderGate = validateBlockOrder({ startBlock: options.startBlock, endBlock: options.endBlock });
  if (!orderGate.ok) return stop(deps, mode, "invalid_block_order", orderGate.reason);

  const rangeGate = validateRangeSize({ startBlock: options.startBlock, endBlock: options.endBlock });
  if (!rangeGate.ok) return stop(deps, mode, "range_too_large", rangeGate.reason);

  // Fork-boundary check: applies identically in both dry-run and execute
  // paths, before any evidence is written or HTTP call made.
  const forkGate = validateForkBoundary({ startBlock: options.startBlock });
  if (!forkGate.ok) return stop(deps, mode, "fork_boundary_violation", forkGate.reason);

  const policyLabelResult = buildPolicyLabel(options.reason);
  if (!policyLabelResult.ok) return stop(deps, mode, "invalid_reason", policyLabelResult.reason);
  const { policyLabel } = policyLabelResult;

  const wallet = await deps.resolveWallet({ walletAddress: options.walletAddress, chainId: options.chainId });
  if (!wallet) return stop(deps, mode, "wallet_not_found");

  const cursorsBefore = await getCursorsForAllFamilies(deps.db, { walletId: wallet.id, chainId: options.chainId });

  if (mode === "dry-run") {
    const disconnection = Object.fromEntries(
      WINDOW_SOURCE_FAMILIES.map((sourceFamily) => [
        sourceFamily,
        classifyCursorDisconnection({
          cursor: cursorsBefore[sourceFamily],
          startBlock: options.startBlock,
          endBlock: options.endBlock,
        }),
      ]),
    );

    await deps.writeEvidence({
      kind: "dry-run",
      at: deps.now().toISOString(),
      mode: "dry-run",
      wallet: { chainId: options.chainId, address: options.walletAddress },
      requestedRange: { startBlock: options.startBlock.toString(), endBlock: options.endBlock.toString() },
      sourceFamilies: [...WINDOW_SOURCE_FAMILIES],
      policyLabel,
      forkClassification: "PULSECHAIN_POST_FORK",
      cursorsBefore: serializeCursors(cursorsBefore),
      disconnectionFromExistingCoverage: disconnection,
      executed: false,
    });

    return { mode, stoppedReason: "dry_run_reported" };
  }

  // ── Execute path ──
  const activeRunCount = await countActiveOperations(deps.db);
  const activeOpGate = validateNoActiveOperation({ activeRunCount });
  if (!activeOpGate.ok) return stop(deps, mode, "active_operation_conflict", activeOpGate.reason);

  const existingLabels = await listActivePolicyLabels(deps.db, options.chainId);
  const labelGate = validateNoPolicyLabelCollision({ policyLabel, existingPolicyLabels: existingLabels });
  if (!labelGate.ok) return stop(deps, mode, "policy_label_collision", labelGate.reason);

  const healthGate = await checkServerHealth(deps.httpGet, options.baseUrl);
  if (!healthGate.ok) return stop(deps, mode, "server_unhealthy", healthGate.reason);

  const submittedAt = deps.now().toISOString();
  const requestBody = buildManualSyncRequestBody({
    walletAddress: options.walletAddress,
    startBlock: options.startBlock,
    endBlock: options.endBlock,
    policyLabel,
  });
  const postResponse = await deps.httpPost(`${options.baseUrl}/api/sync/manual`, requestBody);
  const runId = (postResponse.body as { data?: { runId?: string } } | undefined)?.data?.runId;
  if (postResponse.status !== 202 || !runId) {
    await deps.writeEvidence({
      kind: "stop",
      at: deps.now().toISOString(),
      mode,
      reason: "manual_sync_submit_failed",
      detail: `POST /api/sync/manual returned status ${postResponse.status}`,
      policyLabel,
      submittedAt,
    });
    return { mode, stoppedReason: "manual_sync_submit_failed", detail: `POST /api/sync/manual returned status ${postResponse.status}` };
  }

  const polled = await pollSyncRunToTerminal(deps.db, runId, {
    now: deps.now,
    sleep: deps.sleep,
    pollIntervalMs: options.pollIntervalMs,
    pollTimeoutMs: options.pollTimeoutMs,
  });
  if (!polled.ok) {
    await deps.writeEvidence({
      kind: "stop",
      at: deps.now().toISOString(),
      mode,
      reason: "poll_timeout",
      detail: `SyncRun ${runId} did not reach a terminal state within ${options.pollTimeoutMs}ms`,
      policyLabel,
      runId,
      submittedAt,
    });
    return { mode, stoppedReason: "poll_timeout", detail: `SyncRun ${runId} did not reach a terminal state within ${options.pollTimeoutMs}ms` };
  }
  const terminalAt = deps.now().toISOString();

  const cursorsAfter = await getCursorsForAllFamilies(deps.db, { walletId: wallet.id, chainId: options.chainId });
  const cursorComparison = Object.fromEntries(
    WINDOW_SOURCE_FAMILIES.map((sourceFamily) => [
      sourceFamily,
      {
        before: cursorsBefore[sourceFamily],
        after: cursorsAfter[sourceFamily],
        unchanged: cursorsIdentical(cursorsBefore[sourceFamily], cursorsAfter[sourceFamily]),
      },
    ]),
  );

  const terminalStatus = polled.run.status;
  const succeeded = terminalStatus === "COMPLETED";

  await deps.writeEvidence({
    kind: "execute",
    at: terminalAt,
    mode: "execute",
    wallet: { chainId: options.chainId, address: options.walletAddress },
    submittedRange: { startBlock: options.startBlock.toString(), endBlock: options.endBlock.toString() },
    sourceFamilies: [...WINDOW_SOURCE_FAMILIES],
    policyLabel,
    runId,
    submittedAt,
    terminalAt,
    terminalStatus,
    warningCount: polled.run.warningCount,
    warningDetails: polled.run.warningDetails,
    errorMessage: polled.run.errorMessage,
    cursorComparison: serializeCursorComparison(cursorComparison),
    reorgLimitation: REORG_LIMITATION_DISCLOSURE,
    materializationLimitation: MATERIALIZATION_LIMITATION_DISCLOSURE,
    portfolioTotalsRefreshed: false,
  });

  return {
    mode,
    stoppedReason: succeeded ? "execute_completed" : "sync_run_not_completed",
    detail: succeeded ? undefined : `SyncRun ${runId} terminal status was ${terminalStatus}, not COMPLETED`,
  };
}

function serializeCursors(cursors: Record<string, CursorSnapshot>) {
  return Object.fromEntries(
    Object.entries(cursors).map(([family, cursor]) => [
      family,
      cursor ? { fromBlock: cursor.fromBlock.toString(), toBlock: cursor.toBlock.toString() } : null,
    ]),
  );
}

function serializeCursorComparison(
  comparison: Record<string, { before: CursorSnapshot; after: CursorSnapshot; unchanged: boolean }>,
) {
  return Object.fromEntries(
    Object.entries(comparison).map(([family, entry]) => [
      family,
      {
        before: entry.before ? { fromBlock: entry.before.fromBlock.toString(), toBlock: entry.before.toBlock.toString() } : null,
        after: entry.after ? { fromBlock: entry.after.fromBlock.toString(), toBlock: entry.after.toBlock.toString() } : null,
        unchanged: entry.unchanged,
      },
    ]),
  );
}

async function stop(
  deps: RunnerDeps,
  mode: "dry-run" | "execute",
  reason: string,
  detail?: string,
): Promise<RunnerSummary> {
  await deps.writeEvidence({ kind: "stop", at: deps.now().toISOString(), mode, reason, detail });
  return { mode, stoppedReason: reason, detail };
}

// ─── CLI entrypoint ─────────────────────────────────────────────────────────

function safeStringify(value: unknown): string {
  return JSON.stringify(value, bigintSafeReplacer, 2);
}

const SUCCESSFUL_STOP_REASONS = new Set(["dry_run_reported", "execute_completed"]);

async function main(): Promise<void> {
  const parsed = parseRunnerCliArgs(process.argv.slice(2));
  if (!parsed.ok) {
    console.error(`evidence-directed-window-runner: ${parsed.error}`);
    console.error(RUNNER_CLI_USAGE);
    process.exitCode = 1;
    return;
  }

  const envCheck = checkEnv(process.env as Record<string, string | undefined>);
  if (!envCheck.ok) {
    console.error(
      `evidence-directed-window-runner: missing required environment variables: ${envCheck.missing.join(", ")}`,
    );
    process.exitCode = 1;
    return;
  }

  // Deferred imports so argument/env validation always runs first and the
  // server-only service modules never load for an invalid invocation.
  const { PrismaClient } = await import("@prisma/client");
  const { createPrismaAdapter } = await import("@/lib/prisma-adapter");
  const { resolveTrackedWalletByAddress } = await import("@/services/api/wallets");

  const prisma = new PrismaClient({ adapter: createPrismaAdapter() });

  const deps: RunnerDeps = {
    db: prisma as unknown as RunnerDbClient,
    resolveWallet: resolveTrackedWalletByAddress,
    httpGet: async (url) => {
      const res = await fetch(url);
      return { status: res.status, body: await res.json().catch(() => undefined) };
    },
    httpPost: async (url, body) => {
      const res = await fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      });
      return { status: res.status, body: await res.json().catch(() => undefined) };
    },
    now: () => new Date(),
    sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
    writeEvidence: (record) => writeEvidenceLine(parsed.options.evidenceDir, record),
  };

  try {
    const summary = await runEvidenceDirectedWindowRunner(parsed.options, deps);
    console.log(safeStringify(summary));
    if (!SUCCESSFUL_STOP_REASONS.has(summary.stoppedReason)) {
      process.exitCode = 1;
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`evidence-directed-window-runner error: ${message}`);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`evidence-directed-window-runner error: ${message}`);
    process.exitCode = 1;
  });
}
