/**
 * Evidence-directed multi-family historical window runner — operator utility
 * only.
 *
 * Submits ONE explicitly approved, bounded, post-fork PulseChain historical
 * block window through the existing production sync pipeline
 * (`POST /api/sync/manual`) for all four supported source families at once
 * (`TRANSFERS`, `DEX`, `LP`, `STAKING`). It does not implement a new
 * ingestion architecture, does not modify `runWalletSync` or
 * `mergeCursorWindow`, and does not perform reorg detection or portfolio
 * materialization.
 *
 * A historical window submitted here must be disconnected from the wallet's
 * live SyncCursor for every one of the four families (that is the entire
 * point — it targets a gap the ordinary forward/backfill cursor has not
 * reached). The runner enforces this itself in the execute path (see
 * `validateCursorDisconnection` below) before ever submitting, and
 * `mergeCursorWindow` additionally refuses to move a cursor across a
 * disconnected gap as a second, independent line of defense
 * (src/services/sync/sync-state-store.ts). A successful run here therefore
 * ingests raw + canonical ledger evidence for the window WITHOUT advancing
 * SyncCursor and WITHOUT claiming the wallet's historical coverage is now
 * contiguous. This runner relies on that existing `mergeCursorWindow`
 * invariant as a backstop; it does not attempt to force, bypass, or
 * duplicate it — it refuses connected windows before ever reaching it.
 *
 * Known limitations this runner does NOT attempt to fix (out of scope):
 *   - Reorg detection (`detectReorgMismatch`, `ReorgEvent`,
 *     `markRawDataRangeReorged`) is not wired into production ingestion.
 *     Re-ingesting a block under a genuinely different blockHash is a
 *     pre-existing correctness gap this runner does not address.
 *   - Portfolio materialization: this runner NEVER calls rebuild or any
 *     equivalent materialization operation. PortfolioTokenBalance may remain
 *     stale relative to a newly ingested window until a separately
 *     authorized rebuild runs.
 *
 * Safety defaults:
 *   - Dry-run unless --execute is passed.
 *   - sourceFamilies is fixed to ["TRANSFERS", "DEX", "LP", "STAKING"] and is
 *     NOT an operator-supplied argument.
 *   - The fork-boundary check (classifyPulseChainBlockProvenance) runs in
 *     BOTH the dry-run and execute paths, before any HTTP call.
 *   - The block span is capped by the existing manual-sync limit
 *     (MANUAL_SYNC_MAX_BLOCK_SPAN, src/services/api/validation.ts) — the same
 *     limit POST /api/sync/manual itself enforces.
 *   - The policyLabel prefix `EVIDENCE_DIRECTED_WINDOW_V1:` is generated by
 *     the runner from the operator's `--reason`; the operator cannot type or
 *     override the prefix.
 *
 * Usage (dry-run, the safe default):
 *   npx tsx --conditions react-server scripts/evidence-directed-window-runner.ts \
 *     --wallet-address 0x... --chain-id 369 \
 *     --start-block 17233000 --end-block 17233999 \
 *     --reason "recover window 65 evidence"
 *
 * Usage (execute exactly one window):
 *   npx tsx --conditions react-server scripts/evidence-directed-window-runner.ts \
 *     --execute --wallet-address 0x... --chain-id 369 \
 *     --start-block 17233000 --end-block 17233999 \
 *     --reason "recover window 65 evidence"
 *
 * Required environment variables:
 *   DATABASE_URL  PostgreSQL connection string (direct read-only planning
 *                 queries; all mutations happen through the HTTP route)
 *   REDIS_URL     Redis connection string (required by server-env)
 *
 * The --conditions react-server flag is required because imported ingestion
 * service modules use the server-only guard, which is a no-op only under
 * that export condition.
 *
 * HTTP calls (`GET /api/debug/health`, `POST /api/sync/manual`) carry a
 * fixed request timeout (`HTTP_REQUEST_TIMEOUT_MS`, matching the convention
 * already established in scripts/wallet-forward-campaign-runner.ts and
 * scripts/wallet-forward-supervisor.ts). A timed-out health check fails the
 * health gate closed exactly like any other network error. A timed-out or
 * otherwise-thrown POST is never automatically retried: instead the runner
 * performs a narrow, read-only ambiguous-submission recovery lookup by
 * policyLabel (`classifyAmbiguousSubmissionRecovery`) and only proceeds if
 * canonical PostgreSQL shows exactly one SyncRun matching the full expected
 * identity; any other outcome fails closed with explicit evidence that
 * server acceptance is unknown.
 *
 * Exit behaviour (see `CLEAN_STOP_REASONS`/`computeExitCode`; the same
 * explicit-allowlist, fail-closed design used by
 * scripts/wallet-forward-sync-runner.ts):
 *   - Exits 0 only for `dry_run_reported` or `execute_completed` — the two
 *     stop reasons that represent the runner doing exactly what it was
 *     asked to do.
 *   - Exits 1 for every other stop reason, including invalid arguments,
 *     missing environment, every pre-submit gate decline (wallet not found,
 *     active-operation conflict, policy-label collision, connected-window
 *     rejection, server unhealthy), an unrecoverable ambiguous submission,
 *     HTTP submission failure, poll timeout, or an unterminated/failed
 *     SyncRun. Adding a new stop reason without adding it to
 *     `CLEAN_STOP_REASONS` therefore fails closed (exit 1) rather than
 *     silently succeeding. The JSON summary on stdout always reports the
 *     exact stop reason regardless of exit code.
 *   - Never prints DATABASE_URL, REDIS_URL, RPC URLs, secrets, or headers.
 */

import { fileURLToPath } from "url";
import { mkdir, appendFile } from "node:fs/promises";
import path from "node:path";

import { PULSECHAIN_FORK_BOUNDARY, PULSECHAIN_REFERENCE } from "@/config/chains";
import { classifyPulseChainBlockProvenance } from "@/services/chains/fork-provenance";
import { MANUAL_SYNC_MAX_BLOCK_SPAN } from "@/services/api/validation";

// ─── Fixed policy (not operator-overridable) ───────────────────────────────

export const WINDOW_CHAIN_ID = PULSECHAIN_REFERENCE.id;
export const WINDOW_SOURCE_FAMILIES = ["TRANSFERS", "DEX", "LP", "STAKING"] as const;
export const POLICY_LABEL_PREFIX = "EVIDENCE_DIRECTED_WINDOW_V1:";
export const MAX_REASON_SLUG_LENGTH = 64;

/**
 * Fixed request timeout applied to both the health check and the manual-sync
 * submission, matching the established convention in
 * scripts/wallet-forward-campaign-runner.ts (`HTTP_REQUEST_TIMEOUT_MS`) and
 * scripts/wallet-forward-supervisor.ts. Applies via `AbortSignal.timeout` in
 * `main()`'s real `httpGet`/`httpPost` implementations only — injected test
 * deps are not subject to it. A timed-out GET fails the health gate closed
 * identically to any other network error. A timed-out POST throws exactly
 * like any other transport failure, so it flows through the same
 * ambiguous-submission recovery path — never an automatic retry.
 */
export const HTTP_REQUEST_TIMEOUT_MS = 60_000;

// ─── Reason slug / policyLabel (pure) ──────────────────────────────────────

/**
 * Deterministic lowercase [a-z0-9-] slug from an arbitrary operator reason.
 * Returns null when nothing sanitizable remains (empty, punctuation-only,
 * etc.) so the caller can fail closed rather than submit an empty label.
 */
export function slugifyReason(reason: string): string | null {
  const slug = reason
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, MAX_REASON_SLUG_LENGTH)
    .replace(/-$/g, "");
  return slug.length > 0 ? slug : null;
}

export type PolicyLabelResult =
  | { ok: true; policyLabel: string; slug: string }
  | { ok: false; reason: string };

/**
 * Builds the machine-generated, versioned policyLabel from the operator's
 * reason text. The `EVIDENCE_DIRECTED_WINDOW_V1:` prefix is fixed by this
 * function alone — nothing in the CLI layer can substitute or bypass it.
 */
export function buildPolicyLabel(reasonInput: string): PolicyLabelResult {
  const slug = slugifyReason(reasonInput);
  if (!slug) {
    return { ok: false, reason: "reason produced an empty slug after sanitization; provide a reason containing at least one letter or digit" };
  }
  return { ok: true, policyLabel: `${POLICY_LABEL_PREFIX}${slug}`, slug };
}

// ─── Pre-submit validation gates (pure) ────────────────────────────────────

export type GateResult = { ok: true } | { ok: false; reason: string };

export function validateChainId(chainId: number): GateResult {
  if (chainId !== WINDOW_CHAIN_ID) {
    return { ok: false, reason: `chainId must be ${WINDOW_CHAIN_ID} (PulseChain); got ${chainId}` };
  }
  return { ok: true };
}

export function validateBlockOrder(args: { startBlock: bigint; endBlock: bigint }): GateResult {
  if (args.startBlock > args.endBlock) {
    return { ok: false, reason: `startBlock ${args.startBlock} must be less than or equal to endBlock ${args.endBlock}` };
  }
  return { ok: true };
}

export function validateRangeSize(args: {
  startBlock: bigint;
  endBlock: bigint;
  maxBlockSpan?: bigint;
}): GateResult {
  const maxBlockSpan = args.maxBlockSpan ?? MANUAL_SYNC_MAX_BLOCK_SPAN;
  const span = args.endBlock - args.startBlock;
  if (span > maxBlockSpan) {
    return {
      ok: false,
      reason: `block span ${span} exceeds the operator limit of ${maxBlockSpan} blocks (the same limit POST /api/sync/manual enforces); use a smaller range`,
    };
  }
  return { ok: true };
}

/**
 * Mechanical hard stop against planning or submitting a window whose
 * startBlock does not classify as PULSECHAIN_POST_FORK
 * (`classifyPulseChainBlockProvenance`, src/services/chains/fork-provenance.ts).
 * Runs identically in both the dry-run and execute paths.
 */
export function validateForkBoundary(args: { startBlock: bigint }): GateResult {
  const provenance = classifyPulseChainBlockProvenance({
    chainId: WINDOW_CHAIN_ID,
    blockNumber: args.startBlock,
  });
  if (provenance !== "PULSECHAIN_POST_FORK") {
    return {
      ok: false,
      reason: `proposed startBlock ${args.startBlock} classifies as ${provenance}, not PULSECHAIN_POST_FORK; this runner must never plan or submit a window at or below the PulseChain fork boundary (lastInheritedBlock ${PULSECHAIN_FORK_BOUNDARY.lastInheritedBlock})`,
    };
  }
  return { ok: true };
}

export function validateWalletAddress(walletAddress: string): GateResult {
  if (!/^0x[a-fA-F0-9]{40}$/.test(walletAddress)) {
    return { ok: false, reason: `walletAddress must be a valid EVM address; got ${JSON.stringify(walletAddress)}` };
  }
  return { ok: true };
}

export function validateNoActiveOperation(args: { activeRunCount: number }): GateResult {
  if (args.activeRunCount > 0) {
    return {
      ok: false,
      reason: `${args.activeRunCount} active (PENDING/RUNNING) SyncRun(s) exist; refusing to submit while an operation is active`,
    };
  }
  return { ok: true };
}

export function validateNoPolicyLabelCollision(args: {
  policyLabel: string;
  policyLabelExists: boolean;
}): GateResult {
  if (args.policyLabelExists) {
    return { ok: false, reason: `a SyncRun with policyLabel "${args.policyLabel}" already exists` };
  }
  return { ok: true };
}

// ─── Request body builder (pure) ───────────────────────────────────────────

export function buildManualSyncRequestBody(args: {
  walletAddress: string;
  startBlock: bigint;
  endBlock: bigint;
  policyLabel: string;
}) {
  return {
    walletAddress: args.walletAddress,
    chainId: WINDOW_CHAIN_ID,
    sourceFamilies: [...WINDOW_SOURCE_FAMILIES],
    startBlock: args.startBlock.toString(),
    endBlock: args.endBlock.toString(),
    policyLabel: args.policyLabel,
  };
}

// ─── Cursor disconnection (pure) ───────────────────────────────────────────
//
// Mirrors the disconnected-gap comparison mergeCursorWindow already performs
// (src/services/sync/sync-state-store.ts) so the dry-run report can honestly
// state whether the requested window sits outside the family's existing
// cursor coverage, without re-deriving or duplicating cursor-merge logic.

export type CursorSnapshot = { fromBlock: bigint; toBlock: bigint } | null;

export type CursorDisconnection = "no_existing_cursor" | "disconnected" | "connected";

export function classifyCursorDisconnection(args: {
  cursor: CursorSnapshot;
  startBlock: bigint;
  endBlock: bigint;
}): CursorDisconnection {
  if (!args.cursor) {
    return "no_existing_cursor";
  }
  const disconnectedForward = args.startBlock > args.cursor.toBlock + 1n;
  const disconnectedBackward = args.endBlock + 1n < args.cursor.fromBlock;
  return disconnectedForward || disconnectedBackward ? "disconnected" : "connected";
}

export function cursorsIdentical(a: CursorSnapshot, b: CursorSnapshot): boolean {
  if (a === null && b === null) return true;
  if (a === null || b === null) return false;
  return a.fromBlock === b.fromBlock && a.toBlock === b.toBlock;
}

/**
 * Execute-mode gate: refuses to submit when the requested window is
 * "connected" (overlapping or directly adjacent) to ANY family's existing
 * SyncCursor. A connected window would make `mergeCursorWindow` (called
 * inside `runWalletSync`) actually expand that family's cursor rather than
 * leaving it untouched — silently breaking this runner's documented
 * no-cursor-movement contract for a tool whose entire purpose is targeting
 * an already-disconnected historical gap. `no_existing_cursor` and
 * `disconnected` are both acceptable; only `connected` fails this gate.
 */
export function validateCursorDisconnection(args: {
  cursorsBefore: Record<(typeof WINDOW_SOURCE_FAMILIES)[number], CursorSnapshot>;
  startBlock: bigint;
  endBlock: bigint;
}): GateResult {
  const connectedFamilies = WINDOW_SOURCE_FAMILIES.filter(
    (sourceFamily) =>
      classifyCursorDisconnection({
        cursor: args.cursorsBefore[sourceFamily],
        startBlock: args.startBlock,
        endBlock: args.endBlock,
      }) === "connected",
  );
  if (connectedFamilies.length > 0) {
    return {
      ok: false,
      reason: `requested window [${args.startBlock}, ${args.endBlock}] is connected (overlapping or directly adjacent) to the existing SyncCursor for: ${connectedFamilies.join(", ")}; this runner only targets windows disconnected from all four families' existing coverage`,
    };
  }
  return { ok: true };
}

// ─── CLI argument parsing ───────────────────────────────────────────────────

export type RunnerCliOptions = {
  execute: boolean;
  walletAddress: string;
  chainId: number;
  startBlock: bigint;
  endBlock: bigint;
  reason: string;
  baseUrl: string;
  evidenceDir: string;
  pollIntervalMs: number;
  pollTimeoutMs: number;
};

export type RunnerCliParseResult =
  | { ok: true; options: RunnerCliOptions }
  | { ok: false; error: string };

export const RUNNER_CLI_USAGE = [
  "Usage: evidence-directed-window-runner [--execute]",
  "         --wallet-address <0x..> --chain-id <369>",
  "         --start-block <n> --end-block <n> --reason <text>",
  "         [--base-url <url>] [--evidence-dir <path>]",
  "         [--poll-interval-ms <n>] [--poll-timeout-ms <n>]",
  "",
  "  Dry-run is the default and never submits an HTTP POST.",
  "  sourceFamilies is fixed to [TRANSFERS, DEX, LP, STAKING] and cannot be",
  "  supplied on the command line.",
  "  --wallet-address, --chain-id, --start-block, --end-block, and --reason",
  "  are all required.",
].join("\n");

const DEFAULT_BASE_URL = process.env.OPERATOR_RUNNER_BASE_URL ?? "http://localhost:3000";
const DEFAULT_EVIDENCE_DIR = "operator-evidence/evidence-directed-window";
const DEFAULT_POLL_INTERVAL_MS = 5_000;
const DEFAULT_POLL_TIMEOUT_MS = 20 * 60 * 1000;

export function parseRunnerCliArgs(argv: readonly string[]): RunnerCliParseResult {
  let execute = false;
  let walletAddress: string | undefined;
  let chainId: number | undefined;
  let startBlock: bigint | undefined;
  let endBlock: bigint | undefined;
  let reason: string | undefined;
  let baseUrl = DEFAULT_BASE_URL;
  let evidenceDir = DEFAULT_EVIDENCE_DIR;
  let pollIntervalMs = DEFAULT_POLL_INTERVAL_MS;
  let pollTimeoutMs = DEFAULT_POLL_TIMEOUT_MS;

  const readValue = (flag: string, index: number): string | null => {
    const value = argv[index + 1];
    if (value === undefined || value.startsWith("--")) {
      return null;
    }
    return value;
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--execute") {
      execute = true;
      continue;
    }
    if (arg === "--wallet-address") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--wallet-address requires a value." };
      walletAddress = value.toLowerCase();
      index += 1;
      continue;
    }
    if (arg === "--chain-id") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value)) {
        return { ok: false, error: "--chain-id must be an unsigned integer." };
      }
      chainId = Number(value);
      index += 1;
      continue;
    }
    if (arg === "--start-block") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value)) {
        return { ok: false, error: "--start-block must be an unsigned integer." };
      }
      startBlock = BigInt(value);
      index += 1;
      continue;
    }
    if (arg === "--end-block") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value)) {
        return { ok: false, error: "--end-block must be an unsigned integer." };
      }
      endBlock = BigInt(value);
      index += 1;
      continue;
    }
    if (arg === "--reason") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--reason requires a value." };
      reason = value;
      index += 1;
      continue;
    }
    if (arg === "--base-url") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--base-url requires a value." };
      baseUrl = value;
      index += 1;
      continue;
    }
    if (arg === "--evidence-dir") {
      const value = readValue(arg, index);
      if (value === null) return { ok: false, error: "--evidence-dir requires a value." };
      evidenceDir = value;
      index += 1;
      continue;
    }
    if (arg === "--poll-interval-ms") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value) || Number(value) <= 0) {
        return { ok: false, error: "--poll-interval-ms must be a positive integer." };
      }
      pollIntervalMs = Number(value);
      index += 1;
      continue;
    }
    if (arg === "--poll-timeout-ms") {
      const value = readValue(arg, index);
      if (value === null || !/^\d+$/.test(value) || Number(value) <= 0) {
        return { ok: false, error: "--poll-timeout-ms must be a positive integer." };
      }
      pollTimeoutMs = Number(value);
      index += 1;
      continue;
    }
    if (arg === "--source-families" || arg === "--sourceFamilies") {
      return { ok: false, error: "sourceFamilies is fixed to [TRANSFERS, DEX, LP, STAKING] and cannot be supplied on the command line." };
    }

    return { ok: false, error: `Unknown argument: ${arg}` };
  }

  if (walletAddress === undefined) return { ok: false, error: "--wallet-address is required." };
  if (chainId === undefined) return { ok: false, error: "--chain-id is required." };
  if (startBlock === undefined) return { ok: false, error: "--start-block is required." };
  if (endBlock === undefined) return { ok: false, error: "--end-block is required." };
  if (reason === undefined) return { ok: false, error: "--reason is required." };

  const walletGate = validateWalletAddress(walletAddress);
  if (!walletGate.ok) return { ok: false, error: walletGate.reason };

  return {
    ok: true,
    options: {
      execute,
      walletAddress,
      chainId,
      startBlock,
      endBlock,
      reason,
      baseUrl,
      evidenceDir,
      pollIntervalMs,
      pollTimeoutMs,
    },
  };
}

// ─── Env validation ─────────────────────────────────────────────────────────

const REQUIRED_ENV_VARS = ["DATABASE_URL", "REDIS_URL"] as const;

export type EnvCheckResult = { ok: true } | { ok: false; missing: readonly string[] };

export function checkEnv(env: Record<string, string | undefined>): EnvCheckResult {
  const missing = REQUIRED_ENV_VARS.filter((k) => !env[k]);
  return missing.length === 0 ? { ok: true } : { ok: false, missing };
}

// ─── Evidence records ───────────────────────────────────────────────────────

export type EvidenceRecord = {
  kind: "dry-run" | "execute" | "stop";
  at: string;
  [key: string]: unknown;
};

/** JSON.stringify replacer that serializes bigint as a decimal string. */
function bigintSafeReplacer(_key: string, value: unknown) {
  return typeof value === "bigint" ? value.toString() : value;
}

export function serializeEvidence(record: EvidenceRecord): string {
  return JSON.stringify(record, bigintSafeReplacer);
}

export async function writeEvidenceLine(evidenceDir: string, record: EvidenceRecord): Promise<void> {
  await mkdir(evidenceDir, { recursive: true });
  const filePath = path.join(evidenceDir, "evidence-directed-window-evidence.jsonl");
  await appendFile(filePath, `${serializeEvidence(record)}\n`, "utf8");
}

// ─── Runner DB client (narrow, injectable) ─────────────────────────────────

export type RunnerSyncRunRecord = {
  id: string;
  trigger: string;
  status: string;
  stage: string;
  policyLabel: string;
  sourceFamilies: readonly string[];
  startBlock: bigint | null;
  endBlock: bigint | null;
  warningCount: number;
  warningDetails: unknown;
  errorMessage: string | null;
  failedSourceFamily: string | null;
  failedFromBlock: bigint | null;
  failedToBlock: bigint | null;
};

export type RunnerDbClient = {
  syncCursor: {
    findUnique: (args: unknown) => Promise<{
      fromBlock: bigint;
      toBlock: bigint;
      blockHash: string | null;
    } | null>;
  };
  syncRun: {
    findMany: (args: unknown) => Promise<RunnerSyncRunRecord[]>;
    findUnique: (args: unknown) => Promise<RunnerSyncRunRecord | null>;
    count: (args: unknown) => Promise<number>;
  };
};

export async function getCursorForFamily(
  db: RunnerDbClient,
  args: { walletId: string; chainId: number; sourceFamily: (typeof WINDOW_SOURCE_FAMILIES)[number] },
): Promise<CursorSnapshot> {
  const cursor = await db.syncCursor.findUnique({
    where: {
      walletId_chainId_sourceFamily: {
        walletId: args.walletId,
        chainId: args.chainId,
        sourceFamily: args.sourceFamily,
      },
    },
    select: { fromBlock: true, toBlock: true, blockHash: true },
  });
  return cursor ? { fromBlock: cursor.fromBlock, toBlock: cursor.toBlock } : null;
}

export async function getCursorsForAllFamilies(
  db: RunnerDbClient,
  args: { walletId: string; chainId: number },
): Promise<Record<(typeof WINDOW_SOURCE_FAMILIES)[number], CursorSnapshot>> {
  const entries = await Promise.all(
    WINDOW_SOURCE_FAMILIES.map(async (sourceFamily) => [
      sourceFamily,
      await getCursorForFamily(db, { walletId: args.walletId, chainId: args.chainId, sourceFamily }),
    ] as const),
  );
  return Object.fromEntries(entries) as Record<(typeof WINDOW_SOURCE_FAMILIES)[number], CursorSnapshot>;
}

/**
 * Smallest targeted existence lookup for the exact (chainId, policyLabel)
 * pair — replaces an earlier version that loaded every SyncRun policyLabel
 * for the chain. No schema/index change: this narrows the query at the
 * database layer via `count`, which Prisma can already push into a single
 * COUNT(*) WHERE query without materializing rows.
 */
export async function policyLabelExistsForChain(
  db: RunnerDbClient,
  args: { chainId: number; policyLabel: string },
): Promise<boolean> {
  const count = await db.syncRun.count({ where: { chainId: args.chainId, policyLabel: args.policyLabel } });
  return count > 0;
}

export async function countActiveOperations(db: RunnerDbClient): Promise<number> {
  return db.syncRun.count({ where: { status: { in: ["PENDING", "RUNNING"] } } });
}

/**
 * All canonical SyncRun rows sharing the exact policyLabel, for
 * ambiguous-submission recovery only. `policyLabel` is not database-unique
 * (prisma/schema.prisma: no `@unique`), so more than one row can share a
 * label — the caller must treat that as a red flag, not resolve it here.
 */
export async function findSyncRunsByPolicyLabel(
  db: RunnerDbClient,
  args: { chainId: number; policyLabel: string },
): Promise<RunnerSyncRunRecord[]> {
  return db.syncRun.findMany({ where: { chainId: args.chainId, policyLabel: args.policyLabel } });
}

// ─── HTTP + polling ─────────────────────────────────────────────────────────

export type HttpResponse = { status: number; body: unknown };
export type HttpPost = (url: string, body: unknown) => Promise<HttpResponse>;
export type HttpGet = (url: string) => Promise<HttpResponse>;

const SANITIZED_RESPONSE_TEXT_MAX_LENGTH = 2_000;

/** Key names that must never appear verbatim in evidence, even if a backend
 * response body somehow included one (defense in depth — the API routes
 * this runner calls do not emit these fields today). */
const SECRET_LIKE_KEY_PATTERN =
  /(database_url|redis_url|password|secret|token|api[-_]?key|authorization|cookie)/i;

function redactSecretLikeFields(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(redactSecretLikeFields);
  }
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      out[key] = SECRET_LIKE_KEY_PATTERN.test(key) ? "[redacted]" : redactSecretLikeFields(val);
    }
    return out;
  }
  return value;
}

/**
 * Prepares a backend HTTP response body for inclusion in stop evidence: caps
 * an oversized/non-JSON string body, redacts any secret-like key a JSON body
 * might carry, and never throws. Matches the convention already established
 * in scripts/lib/wallet-forward-sync-primitives.ts.
 */
export function sanitizeBackendResponseBody(body: unknown): unknown {
  if (body === undefined) {
    return null;
  }
  if (typeof body === "string") {
    return body.length > SANITIZED_RESPONSE_TEXT_MAX_LENGTH
      ? `${body.slice(0, SANITIZED_RESPONSE_TEXT_MAX_LENGTH)}...[truncated]`
      : body;
  }
  try {
    return redactSecretLikeFields(body);
  } catch {
    return "[unavailable: response body could not be sanitized]";
  }
}

/** Reads a fetch Response body as JSON when possible, text otherwise, and
 * never throws — an empty or unparseable body degrades to a safe value
 * rather than masking the original HTTP status. */
export async function readHttpResponseBody(res: { text: () => Promise<string> }): Promise<unknown> {
  let text: string;
  try {
    text = await res.text();
  } catch {
    return undefined;
  }
  if (text.length === 0) {
    return undefined;
  }
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

/**
 * Classifies whether an ambiguous POST (the HTTP call itself threw — the
 * runner never received a runId, but the server may have already accepted
 * and persisted the request) can be safely treated as the exact submitted
 * attempt. Mirrors the design in
 * scripts/wallet-forward-campaign-runner.ts:classifyAmbiguousSubmissionRecovery.
 *
 * `candidates` must be every canonical SyncRun row sharing the exact
 * expected (chainId, policyLabel) pair. The candidate-set size is checked
 * FIRST, independent of identity: zero rows or more than one row sharing the
 * label both fail closed immediately — the mere presence of an unrelated
 * same-label row is itself treated as a red flag, not something a
 * coincidental identity match on a different row can paper over. Only when
 * the label uniquely identifies a single row is that row checked against the
 * full expected identity (policyLabel, sourceFamilies === the fixed four,
 * startBlock, endBlock); any mismatch also fails closed. Never an automatic
 * resubmit, and never an inference from range alone.
 */
export function classifyAmbiguousSubmissionRecovery(args: {
  candidates: readonly RunnerSyncRunRecord[];
  expectedPolicyLabel: string;
  expectedStartBlock: bigint;
  expectedEndBlock: bigint;
}): { ok: true; run: RunnerSyncRunRecord } | { ok: false; reason: string } {
  if (args.candidates.length === 0) {
    return {
      ok: false,
      reason: `ambiguous submission for policyLabel "${args.expectedPolicyLabel}": zero SyncRun candidates share this policyLabel — failing closed, no auto-resubmit`,
    };
  }
  if (args.candidates.length > 1) {
    return {
      ok: false,
      reason: `ambiguous submission for policyLabel "${args.expectedPolicyLabel}": ${args.candidates.length} SyncRun candidates share this policyLabel (policyLabel is not database-unique) — failing closed regardless of which one, if any, would otherwise match the full expected identity, no auto-resubmit`,
    };
  }

  const [sole] = args.candidates;
  const matchesFullIdentity =
    sole.policyLabel === args.expectedPolicyLabel &&
    sole.sourceFamilies.length === WINDOW_SOURCE_FAMILIES.length &&
    WINDOW_SOURCE_FAMILIES.every((family, index) => sole.sourceFamilies[index] === family) &&
    sole.startBlock === args.expectedStartBlock &&
    sole.endBlock === args.expectedEndBlock;

  if (!matchesFullIdentity) {
    return {
      ok: false,
      reason: `ambiguous submission for policyLabel "${args.expectedPolicyLabel}": the sole matching-policyLabel SyncRun candidate does not match the full expected identity (policyLabel, sourceFamilies, startBlock, endBlock) — failing closed, no auto-resubmit`,
    };
  }

  return { ok: true, run: sole };
}

export async function checkServerHealth(httpGet: HttpGet, baseUrl: string): Promise<GateResult> {
  let response: HttpResponse;
  try {
    response = await httpGet(`${baseUrl}/api/debug/health`);
  } catch (err) {
    return { ok: false, reason: `health check request failed: ${err instanceof Error ? err.message : String(err)}` };
  }
  const body = response.body as { data?: { status?: string } } | undefined;
  if (response.status !== 200 || body?.data?.status !== "ok") {
    return { ok: false, reason: `server health check did not report ok (status ${response.status})` };
  }
  return { ok: true };
}

export async function pollSyncRunToTerminal(
  db: RunnerDbClient,
  runId: string,
  deps: { now: () => Date; sleep: (ms: number) => Promise<void>; pollIntervalMs: number; pollTimeoutMs: number },
): Promise<{ ok: true; run: RunnerSyncRunRecord } | { ok: false; reason: "timeout"; lastRun: RunnerSyncRunRecord | null }> {
  const deadline = deps.now().getTime() + deps.pollTimeoutMs;

  for (;;) {
    const run = await db.syncRun.findUnique({ where: { id: runId } });
    if (run && (run.status === "COMPLETED" || run.status === "FAILED")) {
      return { ok: true, run };
    }
    if (deps.now().getTime() >= deadline) {
      return { ok: false, reason: "timeout", lastRun: run };
    }
    await deps.sleep(deps.pollIntervalMs);
  }
}

// ─── Orchestrator ───────────────────────────────────────────────────────────

export type RunnerDeps = {
  db: RunnerDbClient;
  resolveWallet: (args: { walletAddress: string; chainId: number }) => Promise<{ id: string; address: string } | null>;
  httpGet: HttpGet;
  httpPost: HttpPost;
  now: () => Date;
  sleep: (ms: number) => Promise<void>;
  writeEvidence: (record: EvidenceRecord) => Promise<void>;
};

export type RunnerSummary = {
  mode: "dry-run" | "execute";
  stoppedReason: string;
  detail?: string;
};

const REORG_LIMITATION_DISCLOSURE =
  "Reorg detection (detectReorgMismatch, ReorgEvent, markRawDataRangeReorged) is NOT wired into production ingestion. This runner does not detect or guard against re-ingesting a block under a different blockHash than a prior observation.";

const MATERIALIZATION_LIMITATION_DISCLOSURE =
  "This runner never calls rebuild or any portfolio materialization operation. Canonical ledger ingestion for this window may complete while PortfolioTokenBalance remains stale relative to it. A separate, explicitly authorized rebuild is required to refresh portfolio totals.";

export async function runEvidenceDirectedWindowRunner(
  options: RunnerCliOptions,
  deps: RunnerDeps,
): Promise<RunnerSummary> {
  const mode: "dry-run" | "execute" = options.execute ? "execute" : "dry-run";

  const chainIdGate = validateChainId(options.chainId);
  if (!chainIdGate.ok) return stop(deps, mode, "invalid_chain_id", chainIdGate.reason);

  const orderGate = validateBlockOrder({ startBlock: options.startBlock, endBlock: options.endBlock });
  if (!orderGate.ok) return stop(deps, mode, "invalid_block_order", orderGate.reason);

  const rangeGate = validateRangeSize({ startBlock: options.startBlock, endBlock: options.endBlock });
  if (!rangeGate.ok) return stop(deps, mode, "range_too_large", rangeGate.reason);

  // Fork-boundary check: applies identically in both dry-run and execute
  // paths, before any evidence is written or HTTP call made.
  const forkGate = validateForkBoundary({ startBlock: options.startBlock });
  if (!forkGate.ok) return stop(deps, mode, "fork_boundary_violation", forkGate.reason);

  const policyLabelResult = buildPolicyLabel(options.reason);
  if (!policyLabelResult.ok) return stop(deps, mode, "invalid_reason", policyLabelResult.reason);
  const { policyLabel } = policyLabelResult;

  const wallet = await deps.resolveWallet({ walletAddress: options.walletAddress, chainId: options.chainId });
  if (!wallet) return stop(deps, mode, "wallet_not_found");

  const cursorsBefore = await getCursorsForAllFamilies(deps.db, { walletId: wallet.id, chainId: options.chainId });

  if (mode === "dry-run") {
    const disconnection = Object.fromEntries(
      WINDOW_SOURCE_FAMILIES.map((sourceFamily) => [
        sourceFamily,
        classifyCursorDisconnection({
          cursor: cursorsBefore[sourceFamily],
          startBlock: options.startBlock,
          endBlock: options.endBlock,
        }),
      ]),
    );

    await deps.writeEvidence({
      kind: "dry-run",
      at: deps.now().toISOString(),
      mode: "dry-run",
      wallet: { chainId: options.chainId, address: options.walletAddress },
      requestedRange: { startBlock: options.startBlock.toString(), endBlock: options.endBlock.toString() },
      sourceFamilies: [...WINDOW_SOURCE_FAMILIES],
      policyLabel,
      forkClassification: "PULSECHAIN_POST_FORK",
      cursorsBefore: serializeCursors(cursorsBefore),
      disconnectionFromExistingCoverage: disconnection,
      executed: false,
    });

    return { mode, stoppedReason: "dry_run_reported" };
  }

  // ── Execute path ──

  // Refuses a window connected to any family's existing cursor BEFORE any
  // other execute-only gate or HTTP call — see validateCursorDisconnection.
  const disconnectionGate = validateCursorDisconnection({
    cursorsBefore,
    startBlock: options.startBlock,
    endBlock: options.endBlock,
  });
  if (!disconnectionGate.ok) return stop(deps, mode, "window_connected_to_existing_cursor", disconnectionGate.reason);

  const activeRunCount = await countActiveOperations(deps.db);
  const activeOpGate = validateNoActiveOperation({ activeRunCount });
  if (!activeOpGate.ok) return stop(deps, mode, "active_operation_conflict", activeOpGate.reason);

  const policyLabelExists = await policyLabelExistsForChain(deps.db, { chainId: options.chainId, policyLabel });
  const labelGate = validateNoPolicyLabelCollision({ policyLabel, policyLabelExists });
  if (!labelGate.ok) return stop(deps, mode, "policy_label_collision", labelGate.reason);

  const healthGate = await checkServerHealth(deps.httpGet, options.baseUrl);
  if (!healthGate.ok) return stop(deps, mode, "server_unhealthy", healthGate.reason);

  const submittedAt = deps.now().toISOString();
  const requestBody = buildManualSyncRequestBody({
    walletAddress: options.walletAddress,
    startBlock: options.startBlock,
    endBlock: options.endBlock,
    policyLabel,
  });

  // The policy-label collision gate above already ran and passed — this
  // POST is the only submission attempt for this policyLabel; a thrown
  // error here (including a request timeout) is never retried, only
  // resolved via the read-only recovery lookup below.
  let postResponse: HttpResponse | undefined;
  let recoveredRunId: string | undefined;
  try {
    postResponse = await deps.httpPost(`${options.baseUrl}/api/sync/manual`, requestBody);
  } catch (err) {
    const candidates = await findSyncRunsByPolicyLabel(deps.db, { chainId: options.chainId, policyLabel });
    const recovery = classifyAmbiguousSubmissionRecovery({
      candidates,
      expectedPolicyLabel: policyLabel,
      expectedStartBlock: options.startBlock,
      expectedEndBlock: options.endBlock,
    });
    if (!recovery.ok) {
      const detail = `POST /api/sync/manual threw (${err instanceof Error ? err.message : String(err)}); server acceptance is unknown; ${recovery.reason}`;
      await deps.writeEvidence({
        kind: "stop",
        at: deps.now().toISOString(),
        mode,
        reason: "ambiguous_submission_unrecoverable",
        detail,
        policyLabel,
        submittedAt,
        serverAcceptanceUnknown: true,
      });
      return { mode, stoppedReason: "ambiguous_submission_unrecoverable", detail };
    }
    recoveredRunId = recovery.run.id;
  }

  const runId =
    recoveredRunId ?? (postResponse?.body as { data?: { runId?: string } } | undefined)?.data?.runId;

  if (!recoveredRunId && (!postResponse || postResponse.status !== 202 || !runId)) {
    await deps.writeEvidence({
      kind: "stop",
      at: deps.now().toISOString(),
      mode,
      reason: "manual_sync_submit_failed",
      detail: `POST /api/sync/manual returned status ${postResponse?.status ?? "unknown"}`,
      policyLabel,
      submittedAt,
      httpStatus: postResponse?.status ?? null,
      responseBody: sanitizeBackendResponseBody(postResponse?.body),
    });
    return {
      mode,
      stoppedReason: "manual_sync_submit_failed",
      detail: `POST /api/sync/manual returned status ${postResponse?.status ?? "unknown"}`,
    };
  }

  // runId is guaranteed defined here: the block above returns unless either
  // recoveredRunId is set or postResponse carried a runId.
  const finalRunId: string = runId!;

  const polled = await pollSyncRunToTerminal(deps.db, finalRunId, {
    now: deps.now,
    sleep: deps.sleep,
    pollIntervalMs: options.pollIntervalMs,
    pollTimeoutMs: options.pollTimeoutMs,
  });
  if (!polled.ok) {
    await deps.writeEvidence({
      kind: "stop",
      at: deps.now().toISOString(),
      mode,
      reason: "poll_timeout",
      detail: `SyncRun ${finalRunId} did not reach a terminal state within ${options.pollTimeoutMs}ms`,
      policyLabel,
      runId: finalRunId,
      submittedAt,
    });
    return { mode, stoppedReason: "poll_timeout", detail: `SyncRun ${finalRunId} did not reach a terminal state within ${options.pollTimeoutMs}ms` };
  }
  const terminalAt = deps.now().toISOString();

  const cursorsAfter = await getCursorsForAllFamilies(deps.db, { walletId: wallet.id, chainId: options.chainId });
  const cursorComparison = Object.fromEntries(
    WINDOW_SOURCE_FAMILIES.map((sourceFamily) => [
      sourceFamily,
      {
        before: cursorsBefore[sourceFamily],
        after: cursorsAfter[sourceFamily],
        unchanged: cursorsIdentical(cursorsBefore[sourceFamily], cursorsAfter[sourceFamily]),
      },
    ]),
  );

  const terminalStatus = polled.run.status;
  const succeeded = terminalStatus === "COMPLETED";

  await deps.writeEvidence({
    kind: "execute",
    at: terminalAt,
    mode: "execute",
    wallet: { chainId: options.chainId, address: options.walletAddress },
    submittedRange: { startBlock: options.startBlock.toString(), endBlock: options.endBlock.toString() },
    sourceFamilies: [...WINDOW_SOURCE_FAMILIES],
    policyLabel,
    runId: finalRunId,
    recoveredFromAmbiguousSubmission: recoveredRunId !== undefined,
    submittedAt,
    terminalAt,
    terminalStatus,
    warningCount: polled.run.warningCount,
    warningDetails: polled.run.warningDetails,
    errorMessage: polled.run.errorMessage,
    cursorComparison: serializeCursorComparison(cursorComparison),
    reorgLimitation: REORG_LIMITATION_DISCLOSURE,
    materializationLimitation: MATERIALIZATION_LIMITATION_DISCLOSURE,
    portfolioTotalsRefreshed: false,
  });

  return {
    mode,
    stoppedReason: succeeded ? "execute_completed" : "sync_run_not_completed",
    detail: succeeded ? undefined : `SyncRun ${finalRunId} terminal status was ${terminalStatus}, not COMPLETED`,
  };
}

function serializeCursors(cursors: Record<string, CursorSnapshot>) {
  return Object.fromEntries(
    Object.entries(cursors).map(([family, cursor]) => [
      family,
      cursor ? { fromBlock: cursor.fromBlock.toString(), toBlock: cursor.toBlock.toString() } : null,
    ]),
  );
}

function serializeCursorComparison(
  comparison: Record<string, { before: CursorSnapshot; after: CursorSnapshot; unchanged: boolean }>,
) {
  return Object.fromEntries(
    Object.entries(comparison).map(([family, entry]) => [
      family,
      {
        before: entry.before ? { fromBlock: entry.before.fromBlock.toString(), toBlock: entry.before.toBlock.toString() } : null,
        after: entry.after ? { fromBlock: entry.after.fromBlock.toString(), toBlock: entry.after.toBlock.toString() } : null,
        unchanged: entry.unchanged,
      },
    ]),
  );
}

async function stop(
  deps: RunnerDeps,
  mode: "dry-run" | "execute",
  reason: string,
  detail?: string,
): Promise<RunnerSummary> {
  await deps.writeEvidence({ kind: "stop", at: deps.now().toISOString(), mode, reason, detail });
  return { mode, stoppedReason: reason, detail };
}

// ─── CLI entrypoint ─────────────────────────────────────────────────────────

function safeStringify(value: unknown): string {
  return JSON.stringify(value, bigintSafeReplacer, 2);
}

/**
 * Explicit allowlist of stop reasons that represent the runner doing exactly
 * what it was asked to do. Everything else fails closed (exit 1) — matching
 * the deliberate design already used by
 * scripts/wallet-forward-sync-runner.ts's CLEAN_STOP_REASONS/computeExitCode:
 * adding a new stop reason without adding it here fails closed rather than
 * silently succeeding.
 */
export const CLEAN_STOP_REASONS: ReadonlySet<string> = new Set(["dry_run_reported", "execute_completed"]);

export function computeExitCode(stoppedReason: string): 0 | 1 {
  return CLEAN_STOP_REASONS.has(stoppedReason) ? 0 : 1;
}

async function main(): Promise<void> {
  const parsed = parseRunnerCliArgs(process.argv.slice(2));
  if (!parsed.ok) {
    console.error(`evidence-directed-window-runner: ${parsed.error}`);
    console.error(RUNNER_CLI_USAGE);
    process.exitCode = 1;
    return;
  }

  const envCheck = checkEnv(process.env as Record<string, string | undefined>);
  if (!envCheck.ok) {
    console.error(
      `evidence-directed-window-runner: missing required environment variables: ${envCheck.missing.join(", ")}`,
    );
    process.exitCode = 1;
    return;
  }

  // Deferred imports so argument/env validation always runs first and the
  // server-only service modules never load for an invalid invocation.
  const { PrismaClient } = await import("@prisma/client");
  const { createPrismaAdapter } = await import("@/lib/prisma-adapter");
  const { resolveTrackedWalletByAddress } = await import("@/services/api/wallets");

  const prisma = new PrismaClient({ adapter: createPrismaAdapter() });

  const deps: RunnerDeps = {
    db: prisma as unknown as RunnerDbClient,
    resolveWallet: resolveTrackedWalletByAddress,
    // Fixed request timeout on both calls (see HTTP_REQUEST_TIMEOUT_MS doc
    // comment). A timed-out GET fails the health gate closed identically to
    // any other network error. A timed-out POST throws exactly like any
    // other transport failure, so it flows through the orchestrator's
    // ambiguous-submission recovery path unchanged — never an automatic
    // retry of the POST itself.
    httpGet: async (url) => {
      const res = await fetch(url, { signal: AbortSignal.timeout(HTTP_REQUEST_TIMEOUT_MS) });
      return { status: res.status, body: await readHttpResponseBody(res) };
    },
    httpPost: async (url, body) => {
      const res = await fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(HTTP_REQUEST_TIMEOUT_MS),
      });
      return { status: res.status, body: await readHttpResponseBody(res) };
    },
    now: () => new Date(),
    sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
    writeEvidence: (record) => writeEvidenceLine(parsed.options.evidenceDir, record),
  };

  try {
    const summary = await runEvidenceDirectedWindowRunner(parsed.options, deps);
    console.log(safeStringify(summary));
    process.exitCode = computeExitCode(summary.stoppedReason);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`evidence-directed-window-runner error: ${message}`);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`evidence-directed-window-runner error: ${message}`);
    process.exitCode = 1;
  });
}
